name: Plugin Install

on: [push, pull_request, workflow_dispatch]

jobs:
  plugin-install:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        jdk: [11, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Assemble target plugin
        run: ./gradlew assemble


      - name: Create Setup Script for Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          cat > setup.sh <<EOF
          chmod +x ./opensearch/plugins/opensearch-security/tools/install_demo_configuration.sh
          yes | ./opensearch/plugins/opensearch-security/tools/install_demo_configuration.sh
          echo plugins.security.unsupported.restapi.allow_securityconfig_modification: true >> config/opensearch.yml
          EOF

      - name: Create Setup Script for Windows
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          New-Item $pwd\setup.bat
          echo 'y', 'y', 'N' | $(pwd)\opensearch-3.0.0-SNAPSHOT\plugins\opensearch-security\tools\install_demo_configuration.bat >> setup.bat

      - name: Run Opensearch with A Single Plugin
        uses: ./.github/actions/start-opensearch-with-one-plugin
        with:
          opensearch-version: 3.0.0
          plugin-name: opensearch-security
          plugin-setup-script: setup
          docker-host-plugin-zip: security-plugin.zip

      - name: Run sanity tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: integTestRemote -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="opensearch" -Dhttps=true -Duser=admin -Dpassword=admin
